version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
      nodejs: 10
  pre_build:
    commands:
      - echo Mike Testing pipeline
      - aws --version
  build:
    commands:
      - echo Build started on `date`
      - bash helloworld.sh
  post_build:
    commands:
      - echo Build completed on `date`
